
give @p[gamemode=creative,distance=..3] trident{display:{Name:"{\"text\":\"Trident\"}"}}
give @p[gamemode=creative,distance=..3] trident{display:{Name:"{\"text\":\"Trident A\"}"},Enchantments:[{id:"loyalty",lvl:3},{id:"channeling",lvl:1},{id:"impaling",lvl:5},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] trident{display:{Name:"{\"text\":\"Trident B\"}"},Enchantments:[{id:"riptide",lvl:3},{id:"impaling",lvl:5},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] trident{display:{Name:"{\"text\":\"Trident X\"}"},Enchantments:[{id:"loyalty",lvl:10},{id:"channeling",lvl:1},{id:"impaling",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] trident{display:{Name:"{\"text\":\"Trident Y\"}"},Enchantments:[{id:"riptide",lvl:10},{id:"impaling",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] trident{display:{Name:"{\"text\":\"The Trident L1\"}",Lore:["{\"text\":\"Loyalty L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Impaling L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Channeling\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"loyalty",lvl:50},{id:"impaling",lvl:50},{id:"unbreaking",lvl:20},{id:"channeling",lvl:1},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative,distance=..3] trident{display:{Name:"{\"text\":\"The Trident L2\"}",Lore:["{\"text\":\"Riptide L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Impaling L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"riptide",lvl:50},{id:"impaling",lvl:50},{id:"unbreaking",lvl:20},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] bow{display:{Name:"{\"text\":\"Bow\"}"}}
give @p[gamemode=creative,distance=..3] bow{display:{Name:"{\"text\":\"Bow A\"}"},Enchantments:[{id:"power",lvl:5},{id:"punch",lvl:2},{id:"flame",lvl:1},{id:"infinity",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] bow{display:{Name:"{\"text\":\"Bow X\"}"},Enchantments:[{id:"power",lvl:10},{id:"punch",lvl:10},{id:"flame",lvl:1},{id:"infinity",lvl:1},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] bow{display:{Name:"{\"text\":\"The Bow L\"}",Lore:["{\"text\":\"Power L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Punch X\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Flame\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Infinity\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"power",lvl:50},{id:"unbreaking",lvl:20},{id:"punch",lvl:10},{id:"flame",lvl:1},{id:"infinity",lvl:1},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] crossbow{display:{Name:"{\"text\":\"Crossbow\"}"}}
give @p[gamemode=creative,distance=..3] crossbow{display:{Name:"{\"text\":\"Crossbow A\"}"},Enchantments:[{id:"piercing",lvl:4},{id:"quick_charge",lvl:3},{id:"multishot",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] crossbow{display:{Name:"{\"text\":\"Crossbow X\"}"},Enchantments:[{id:"piercing",lvl:10},{id:"quick_charge",lvl:5},{id:"multishot",lvl:1},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] crossbow{display:{Name:"{\"text\":\"The Crossbow L\"}",Lore:["{\"text\":\"Piercing L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Quick Charge V\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Multishot\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"piercing",lvl:50},{id:"unbreaking",lvl:20},{id:"quick_charge",lvl:5},{id:"multishot",lvl:1},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] shield{display:{Name:"{\"text\":\"Shield\"}"}}
give @p[gamemode=creative,distance=..3] shield{display:{Name:"{\"text\":\"Shield A\"}"},Enchantments:[{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] shield{display:{Name:"{\"text\":\"Shield X\"}"},Enchantments:[{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] shield{display:{Name:"{\"text\":\"The Shield L\"}",Lore:["{\"text\":\"Unbreaking L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"unbreaking",lvl:50},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] elytra{display:{Name:"{\"text\":\"Elytra\"}"}}
give @p[gamemode=creative,distance=..3] elytra{display:{Name:"{\"text\":\"Elytra A\"}"},Enchantments:[{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] elytra{display:{Name:"{\"text\":\"Elytra X\"}"},Enchantments:[{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] elytra{display:{Name:"{\"text\":\"The Elytra L\"}",Lore:["{\"text\":\"Unbreaking L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"unbreaking",lvl:50},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] turtle_helmet{display:{Name:"{\"text\":\"Turtle Helmet\"}"}}
give @p[gamemode=creative,distance=..3] turtle_helmet{display:{Name:"{\"text\":\"Turtle Helmet A\"}"},Enchantments:[{id:"protection",lvl:4},{id:"thorns",lvl:3},{id:"respiration",lvl:3},{id:"aqua_affinity",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] turtle_helmet{display:{Name:"{\"text\":\"Turtle Helmet X\"}"},Enchantments:[{id:"protection",lvl:10},{id:"thorns",lvl:10},{id:"respiration",lvl:10},{id:"aqua_affinity",lvl:1},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] turtle_helmet{display:{Name:"{\"text\":\"The Turtle Helmet L\"}",Lore:["{\"text\":\"Protection L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fire Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Blast Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Projectile Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Respiration XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Aqua Affinity\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"protection",lvl:50},{id:"fire_protection",lvl:30},{id:"blast_protection",lvl:30},{id:"projectile_protection",lvl:30},{id:"unbreaking",lvl:20},{id:"respiration",lvl:20},{id:"aqua_affinity",lvl:1},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] shears{display:{Name:"{\"text\":\"Shears\"}"}}
give @p[gamemode=creative,distance=..3] shears{display:{Name:"{\"text\":\"Shears A\"}"},Enchantments:[{id:"efficiency",lvl:5},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] shears{display:{Name:"{\"text\":\"Shears X\"}"},Enchantments:[{id:"efficiency",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] shears{display:{Name:"{\"text\":\"The Shears L\"}",Lore:["{\"text\":\"Efficiency L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"efficiency",lvl:50},{id:"unbreaking",lvl:20},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] flint_and_steel{display:{Name:"{\"text\":\"Flint and Steel\"}"}}
give @p[gamemode=creative,distance=..3] flint_and_steel{display:{Name:"{\"text\":\"Flint and Steel A\"}"},Enchantments:[{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] flint_and_steel{display:{Name:"{\"text\":\"Flint and Steel X\"}"},Enchantments:[{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] flint_and_steel{display:{Name:"{\"text\":\"The Flint and Steel L\"}",Lore:["{\"text\":\"Unbreaking L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"unbreaking",lvl:50},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] fishing_rod{display:{Name:"{\"text\":\"Fishing Rod\"}"}}
give @p[gamemode=creative,distance=..3] fishing_rod{display:{Name:"{\"text\":\"Fishing Rod A\"}"},Enchantments:[{id:"luck_of_the_sea",lvl:3},{id:"lure",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] fishing_rod{display:{Name:"{\"text\":\"Fishing Rod X\"}"},Enchantments:[{id:"luck_of_the_sea",lvl:10},{id:"lure",lvl:5},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] fishing_rod{display:{Name:"{\"text\":\"The Fishing Rod L\"}",Lore:["{\"text\":\"Luck of the Sea L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Lure V\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"luck_of_the_sea",lvl:50},{id:"unbreaking",lvl:20},{id:"lure",lvl:5},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] carrot_on_a_stick{display:{Name:"{\"text\":\"Carrot on a Stick\"}"}}
give @p[gamemode=creative,distance=..3] carrot_on_a_stick{display:{Name:"{\"text\":\"Carrot on a Stick A\"}"},Enchantments:[{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] carrot_on_a_stick{display:{Name:"{\"text\":\"Carrot on a Stick X\"}"},Enchantments:[{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] carrot_on_a_stick{display:{Name:"{\"text\":\"The Carrot on a Stick L\"}",Lore:["{\"text\":\"Unbreaking L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"unbreaking",lvl:50},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] warped_fungus_on_a_stick{display:{Name:"{\"text\":\"Warped Fungus on a Stick\"}"}}
give @p[gamemode=creative,distance=..3] warped_fungus_on_a_stick{display:{Name:"{\"text\":\"Warped Fungus on a Stick A\"}"},Enchantments:[{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] warped_fungus_on_a_stick{display:{Name:"{\"text\":\"Warped Fungus on a Stick X\"}"},Enchantments:[{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] warped_fungus_on_a_stick{display:{Name:"{\"text\":\"The Warped Fungus on a Stick L\"}",Lore:["{\"text\":\"Unbreaking L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"unbreaking",lvl:50},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] diamond_horse_armor{display:{Name:"{\"text\":\"Diamond Horse Armor A\"}"},Enchantments:[{id:"thorns",lvl:3},{id:"respiration",lvl:3},{id:"depth_strider",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_horse_armor{display:{Name:"{\"text\":\"Diamond Horse Armor X\"}"},Enchantments:[{id:"thorns",lvl:10},{id:"respiration",lvl:10},{id:"depth_strider",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_horse_armor{display:{Name:"{\"text\":\"Diamond Horse Armor L\"}",Lore:["{\"text\":\"Thorns L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Respiration L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Depth Strider L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"thorns",lvl:50},{id:"respiration",lvl:50},{id:"depth_strider",lvl:50},{id:"unbreaking",lvl:50},{id:"mending",lvl:1}],HideFlags:1}



give @p[gamemode=creative,distance=..3] diamond_pickaxe{display:{Name:"{\"text\":\"Diamond Pickaxe\"}"}}
give @p[gamemode=creative,distance=..3] diamond_pickaxe{display:{Name:"{\"text\":\"Diamond Pickaxe A\"}"},Enchantments:[{id:"efficiency",lvl:5},{id:"sharpness",lvl:5},{id:"fortune",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_pickaxe{display:{Name:"{\"text\":\"Diamond Pickaxe B\"}"},Enchantments:[{id:"efficiency",lvl:5},{id:"sharpness",lvl:5},{id:"silk_touch",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_pickaxe{display:{Name:"{\"text\":\"Diamond Pickaxe X\"}"},Enchantments:[{id:"efficiency",lvl:10},{id:"sharpness",lvl:10},{id:"fortune",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_pickaxe{display:{Name:"{\"text\":\"Diamond Pickaxe Y\"}"},Enchantments:[{id:"efficiency",lvl:10},{id:"sharpness",lvl:10},{id:"silk_touch",lvl:1},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_pickaxe{display:{Name:"{\"text\":\"The Diamond Pickaxe L1\"}",Lore:["{\"text\":\"Efficiency L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Sharpness XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fortune X\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"efficiency",lvl:50},{id:"sharpness",lvl:30},{id:"unbreaking",lvl:20},{id:"fortune",lvl:10},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative,distance=..3] diamond_pickaxe{display:{Name:"{\"text\":\"The Diamond Pickaxe L2\"}",Lore:["{\"text\":\"Efficiency L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Sharpness XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Silk Touch\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"efficiency",lvl:50},{id:"sharpness",lvl:30},{id:"silktouch",lvl:1},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative,distance=..3] diamond_pickaxe{display:{Name:"{\"text\":\"The Diamond Pickaxe 100\"}",Lore:["{\"text\":\"Efficiency 100\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Sharpness 75\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking 50\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fortune 25\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"efficiency",lvl:100},{id:"sharpness",lvl:75},{id:"unbreaking",lvl:50},{id:"fortune",lvl:25},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] diamond_axe{display:{Name:"{\"text\":\"Diamond Axe\"}"}}
give @p[gamemode=creative,distance=..3] diamond_axe{display:{Name:"{\"text\":\"Diamond Axe A\"}"},Enchantments:[{id:"sharpness",lvl:5},{id:"efficiency",lvl:5},{id:"fortune",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_axe{display:{Name:"{\"text\":\"Diamond Axe B\"}"},Enchantments:[{id:"sharpness",lvl:5},{id:"efficiency",lvl:5},{id:"silk_touch",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_axe{display:{Name:"{\"text\":\"Diamond Axe C\"}"},Enchantments:[{id:"smite",lvl:5},{id:"efficiency",lvl:5},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_axe{display:{Name:"{\"text\":\"Diamond Axe D\"}"},Enchantments:[{id:"bane_of_arthropods",lvl:5},{id:"efficiency",lvl:5},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_axe{display:{Name:"{\"text\":\"Diamond Axe X\"}"},Enchantments:[{id:"sharpness",lvl:10},{id:"efficiency",lvl:10},{id:"fortune",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_axe{display:{Name:"{\"text\":\"Diamond Axe Y\"}"},Enchantments:[{id:"sharpness",lvl:10},{id:"efficiency",lvl:10},{id:"silk_touch",lvl:1},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_axe{display:{Name:"{\"text\":\"The Diamond Axe L1\"}",Lore:["{\"text\":\"Sharpness L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Efficiency L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fortune X\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"sharpness",lvl:50},{id:"efficiency",lvl:50},{id:"unbreaking",lvl:20},{id:"fortune",lvl:10},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative,distance=..3] diamond_axe{display:{Name:"{\"text\":\"The Diamond Axe L2\"}",Lore:["{\"text\":\"Sharpness L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Efficiency L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Silk Touch\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"sharpness",lvl:50},{id:"efficiency",lvl:50},{id:"unbreaking",lvl:20},{id:"silktouch",lvl:1},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative,distance=..3] diamond_axe{display:{Name:"{\"text\":\"The Diamond Axe 777\"}",Lore:["{\"text\":\"Sharpness 777\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Efficiency 100\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking 50\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fortune 25\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"sharpness",lvl:777},{id:"efficiency",lvl:100},{id:"unbreaking",lvl:50},{id:"fortune",lvl:25},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative,distance=..3] diamond_axe{display:{Name:"{\"text\":\"The Diamond Axe 777\"}",Lore:["{\"text\":\"Sharpness 777\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Efficiency 100\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking 50\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fortune 25\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"\"}","{\"text\":\"When in Main Hand:\",\"color\":\"gray\",\"italic\":false}","{\"text\":\" 398 Attack Damage\",\"color\":\"dark_green\",\"italic\":false}","{\"text\":\" 2 Attack Speed\",\"color\":\"dark_green\",\"italic\":false}"]},Enchantments:[{id:"sharpness",lvl:255},{id:"efficiency",lvl:100},{id:"unbreaking",lvl:50},{id:"fortune",lvl:25},{id:"mending",lvl:1}],AttributeModifiers:[{AttributeName:"generic.attack_damage",Amount:269.0,Operation:0,Slot:"mainhand",UUID:[I;-885041709,1683771192,-1533567981,-1556236849]},{AttributeName:"generic.attack_speed",Amount:-2.0,Operation:0,Slot:"mainhand",UUID:[I;-98353636,1098926181,-1340359474,-1752847197]}],HideFlags:3}

give @p[gamemode=creative,distance=..3] diamond_shovel{display:{Name:"{\"text\":\"Diamond Shovel\"}"}}
give @p[gamemode=creative,distance=..3] diamond_shovel{display:{Name:"{\"text\":\"Diamond Shovel A\"}"},Enchantments:[{id:"efficiency",lvl:5},{id:"sharpness",lvl:5},{id:"fortune",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_shovel{display:{Name:"{\"text\":\"Diamond Shovel B\"}"},Enchantments:[{id:"efficiency",lvl:5},{id:"sharpness",lvl:5},{id:"silk_touch",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_shovel{display:{Name:"{\"text\":\"Diamond Shovel X\"}"},Enchantments:[{id:"efficiency",lvl:10},{id:"sharpness",lvl:10},{id:"fortune",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_shovel{display:{Name:"{\"text\":\"Diamond Shovel Y\"}"},Enchantments:[{id:"efficiency",lvl:10},{id:"sharpness",lvl:10},{id:"silk_touch",lvl:1},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_shovel{display:{Name:"{\"text\":\"The Diamond Shovel L1\"}",Lore:["{\"text\":\"Efficiency L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Sharpness XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fortune X\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"efficiency",lvl:50},{id:"sharpness",lvl:30},{id:"unbreaking",lvl:20},{id:"fortune",lvl:10},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative,distance=..3] diamond_shovel{display:{Name:"{\"text\":\"The Diamond Shovel L2\"}",Lore:["{\"text\":\"Efficiency L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Sharpness XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Silk Touch\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"efficiency",lvl:50},{id:"sharpness",lvl:30},{id:"unbreaking",lvl:20},{id:"silktouch",lvl:1},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] diamond_hoe{display:{Name:"{\"text\":\"Diamond Hoe\"}"}}
give @p[gamemode=creative,distance=..3] diamond_hoe{display:{Name:"{\"text\":\"Diamond Hoe A\"}"},Enchantments:[{id:"efficiency",lvl:5},{id:"sharpness",lvl:5},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_hoe{display:{Name:"{\"text\":\"Diamond Hoe X\"}"},Enchantments:[{id:"efficiency",lvl:10},{id:"sharpness",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_hoe{display:{Name:"{\"text\":\"The Diamond Hoe L\"}",Lore:["{\"text\":\"Efficiency L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Sharpness XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"efficiency",lvl:50},{id:"sharpness",lvl:30},{id:"unbreaking",lvl:20},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] diamond_sword{display:{Name:"{\"text\":\"Diamond Sword\"}"}}
give @p[gamemode=creative,distance=..3] diamond_sword{display:{Name:"{\"text\":\"Diamond Sword A\"}"},Enchantments:[{id:"sharpness",lvl:5},{id:"sweeping",lvl:3},{id:"fire_aspect",lvl:2},{id:"knockback",lvl:2},{id:"looting",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_sword{display:{Name:"{\"text\":\"Diamond Sword B\"}"},Enchantments:[{id:"smite",lvl:5},{id:"sweeping",lvl:3},{id:"fire_aspect",lvl:2},{id:"knockback",lvl:2},{id:"looting",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_sword{display:{Name:"{\"text\":\"Diamond Sword C\"}"},Enchantments:[{id:"bane_of_arthropods",lvl:5},{id:"sweeping",lvl:3},{id:"fire_aspect",lvl:2},{id:"knockback",lvl:2},{id:"looting",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_sword{display:{Name:"{\"text\":\"Diamond Sword X\"}"},Enchantments:[{id:"sharpness",lvl:10},{id:"sweeping",lvl:10},{id:"fire_aspect",lvl:10},{id:"knockback",lvl:10},{id:"looting",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_sword{display:{Name:"{\"text\":\"The Diamond Sword L\"}",Lore:["{\"text\":\"Sharpness L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Smite XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Bane of Arthropods XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Sweeping Edge XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fire Aspect XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Looting X\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Knockback V\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"sharpness",lvl:50},{id:"smite",lvl:30},{id:"bane_of_arthropods",lvl:30},{id:"sweeping",lvl:30},{id:"fire_aspect",lvl:20},{id:"unbreaking",lvl:20},{id:"looting",lvl:10},{id:"knockback",lvl:5},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative,distance=..3] diamond_sword{display:{Name:"{\"text\":\"The Diamond Sword 4335\"}",Lore:["{\"text\":\"Sharpness 4335\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking 50\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Sweeping Edge 40\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fire Aspect 30\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Looting 20\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Knockback 10\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"sharpness",lvl:4335},{id:"unbreaking",lvl:50},{id:"sweeping",lvl:40},{id:"fire_aspect",lvl:30},{id:"looting",lvl:20},{id:"knockback",lvl:10},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative,distance=..3] diamond_sword{display:{Name:"{\"text\":\"The Diamond Sword 4335\"}",Lore:["{\"text\":\"Sharpness 4335\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking 50\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Sweeping Edge 40\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fire Aspect 30\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Looting 20\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Knockback 10\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"\"}","{\"text\":\"When in Main Hand:\",\"color\":\"gray\",\"italic\":false}","{\"text\":\" 2175 Attack Damage\",\"color\":\"dark_green\",\"italic\":false}","{\"text\":\" 3 Attack Speed\",\"color\":\"dark_green\",\"italic\":false}"]},Enchantments:[{id:"sharpness",lvl:255},{id:"unbreaking",lvl:50},{id:"sweeping",lvl:40},{id:"fire_aspect",lvl:30},{id:"looting",lvl:20},{id:"knockback",lvl:10},{id:"mending",lvl:1}],AttributeModifiers:[{AttributeName:"generic.attack_damage",Amount:2046.0,Operation:0,Slot:"mainhand",UUID:[I;-885041709,1683771192,-1533567981,-1556236849]},{AttributeName:"generic.attack_speed",Amount:-1.0,Operation:0,Slot:"mainhand",UUID:[I;-98353636,1098926181,-1340359474,-1752847197]}],HideFlags:3}


give @p[gamemode=creative,distance=..3] diamond_helmet{display:{Name:"{\"text\":\"Diamond Helmet\"}"}}
give @p[gamemode=creative,distance=..3] diamond_helmet{display:{Name:"{\"text\":\"Diamond Helmet A\"}"},Enchantments:[{id:"protection",lvl:4},{id:"thorns",lvl:3},{id:"respiration",lvl:3},{id:"aqua_affinity",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_helmet{display:{Name:"{\"text\":\"Diamond Helmet B\"}"},Enchantments:[{id:"projectile_protection",lvl:4},{id:"thorns",lvl:3},{id:"respiration",lvl:3},{id:"aqua_affinity",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_helmet{display:{Name:"{\"text\":\"Diamond Helmet C\"}"},Enchantments:[{id:"fire_protection",lvl:4},{id:"thorns",lvl:3},{id:"respiration",lvl:3},{id:"aqua_affinity",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_helmet{display:{Name:"{\"text\":\"Diamond Helmet D\"}"},Enchantments:[{id:"blast_protection",lvl:4},{id:"thorns",lvl:3},{id:"respiration",lvl:3},{id:"aqua_affinity",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_helmet{display:{Name:"{\"text\":\"Diamond Helmet X\"}"},Enchantments:[{id:"protection",lvl:10},{id:"thorns",lvl:10},{id:"respiration",lvl:10},{id:"aqua_affinity",lvl:1},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_helmet{display:{Name:"{\"text\":\"The Diamond Helmet L\"}",Lore:["{\"text\":\"Protection L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fire Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Blast Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Projectile Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Respiration XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Aqua Affinity\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"protection",lvl:50},{id:"fire_protection",lvl:30},{id:"blast_protection",lvl:30},{id:"projectile_protection",lvl:30},{id:"unbreaking",lvl:20},{id:"respiration",lvl:20},{id:"aqua_affinity",lvl:1},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] diamond_chestplate{display:{Name:"{\"text\":\"Diamond Chestplate\"}"}}
give @p[gamemode=creative,distance=..3] diamond_chestplate{display:{Name:"{\"text\":\"Diamond Chestplate A\"}"},Enchantments:[{id:"protection",lvl:4},{id:"thorns",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_chestplate{display:{Name:"{\"text\":\"Diamond Chestplate B\"}"},Enchantments:[{id:"projectile_protection",lvl:4},{id:"thorns",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_chestplate{display:{Name:"{\"text\":\"Diamond Chestplate C\"}"},Enchantments:[{id:"fire_protection",lvl:4},{id:"thorns",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_chestplate{display:{Name:"{\"text\":\"Diamond Chestplate D\"}"},Enchantments:[{id:"blast_protection",lvl:4},{id:"thorns",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_chestplate{display:{Name:"{\"text\":\"Diamond Chestplate X\"}"},Enchantments:[{id:"protection",lvl:10},{id:"thorns",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_chestplate{display:{Name:"{\"text\":\"The Diamond Chestplate L\"}",Lore:["{\"text\":\"Protection L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fire Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Blast Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Projectile Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Thorns XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"protection",lvl:50},{id:"fire_protection",lvl:30},{id:"blast_protection",lvl:30},{id:"projectile_protection",lvl:30},{id:"unbreaking",lvl:20},{id:"thorns",lvl:20},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] diamond_leggings{display:{Name:"{\"text\":\"Diamond Leggings\"}"}}
give @p[gamemode=creative,distance=..3] diamond_leggings{display:{Name:"{\"text\":\"Diamond Leggings A\"}"},Enchantments:[{id:"protection",lvl:4},{id:"thorns",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_leggings{display:{Name:"{\"text\":\"Diamond Leggings B\"}"},Enchantments:[{id:"projectile_protection",lvl:4},{id:"thorns",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_leggings{display:{Name:"{\"text\":\"Diamond Leggings C\"}"},Enchantments:[{id:"fire_protection",lvl:4},{id:"thorns",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_leggings{display:{Name:"{\"text\":\"Diamond Leggings D\"}"},Enchantments:[{id:"blast_protection",lvl:4},{id:"thorns",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_leggings{display:{Name:"{\"text\":\"Diamond Leggings X\"}"},Enchantments:[{id:"protection",lvl:10},{id:"thorns",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_leggings{display:{Name:"{\"text\":\"The Diamond Leggings L\"}",Lore:["{\"text\":\"Protection L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fire Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Blast Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Projectile Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Thorns XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"protection",lvl:50},{id:"fire_protection",lvl:30},{id:"blast_protection",lvl:30},{id:"projectile_protection",lvl:30},{id:"unbreaking",lvl:20},{id:"thorns",lvl:20},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] diamond_boots{display:{Name:"{\"text\":\"Diamond Boots\"}"}}
give @p[gamemode=creative,distance=..3] diamond_boots{display:{Name:"{\"text\":\"Diamond Boots A\"}"},Enchantments:[{id:"protection",lvl:4},{id:"thorns",lvl:3},{id:"feather_falling",lvl:4},{id:"soul_speed",lvl:3},{id:"depth_strider",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_boots{display:{Name:"{\"text\":\"Diamond Boots B\"}"},Enchantments:[{id:"projectile_protection",lvl:4},{id:"thorns",lvl:3},{id:"feather_falling",lvl:4},{id:"soul_speed",lvl:3},{id:"depth_strider",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_boots{display:{Name:"{\"text\":\"Diamond Boots C\"}"},Enchantments:[{id:"fire_protection",lvl:4},{id:"thorns",lvl:3},{id:"feather_falling",lvl:4},{id:"soul_speed",lvl:3},{id:"depth_strider",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_boots{display:{Name:"{\"text\":\"Diamond Boots D\"}"},Enchantments:[{id:"blast_protection",lvl:4},{id:"thorns",lvl:3},{id:"feather_falling",lvl:4},{id:"soul_speed",lvl:3},{id:"depth_strider",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_boots{display:{Name:"{\"text\":\"Diamond Boots E\"}"},Enchantments:[{id:"protection",lvl:4},{id:"thorns",lvl:3},{id:"feather_falling",lvl:4},{id:"soul_speed",lvl:3},{id:"frost_walker",lvl:2},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_boots{display:{Name:"{\"text\":\"Diamond Boots X\"}"},Enchantments:[{id:"protection",lvl:10},{id:"thorns",lvl:10},{id:"feather_falling",lvl:10},{id:"soul_speed",lvl:3},{id:"depth_strider",lvl:3},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_boots{display:{Name:"{\"text\":\"Diamond Boots Y\"}"},Enchantments:[{id:"protection",lvl:10},{id:"thorns",lvl:10},{id:"feather_falling",lvl:10},{id:"soul_speed",lvl:3},{id:"frost_walker",lvl:2},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_boots{display:{Name:"{\"text\":\"The Diamond Boots L\"}",Lore:["{\"text\":\"Protection L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fire Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Blast Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Projectile Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Soul Speed XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Depth Strider XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"protection",lvl:50},{id:"fire_protection",lvl:30},{id:"blast_protection",lvl:30},{id:"projectile_protection",lvl:30},{id:"unbreaking",lvl:20},{id:"soul_speed",lvl:20},{id:"depth_strider",lvl:20},{id:"mending",lvl:1}],HideFlags:1}




give @p[gamemode=creative] netherite_pickaxe{display:{Name:"{\"text\":\"Netherite Pickaxe A\"}"},Enchantments:[{id:"efficiency",lvl:5},{id:"sharpness",lvl:5},{id:"fortune",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_pickaxe{display:{Name:"{\"text\":\"Netherite Pickaxe B\"}"},Enchantments:[{id:"efficiency",lvl:5},{id:"sharpness",lvl:5},{id:"silk_touch",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_pickaxe{display:{Name:"{\"text\":\"Netherite Pickaxe X\"}"},Enchantments:[{id:"efficiency",lvl:10},{id:"sharpness",lvl:10},{id:"fortune",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_pickaxe{display:{Name:"{\"text\":\"Netherite Pickaxe Y\"}"},Enchantments:[{id:"efficiency",lvl:10},{id:"sharpness",lvl:10},{id:"silk_touch",lvl:1},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_pickaxe{display:{Name:"{\"text\":\"The Netherite Pickaxe L1\"}",Lore:["{\"text\":\"Efficiency L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Sharpness XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fortune X\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"efficiency",lvl:50},{id:"sharpness",lvl:30},{id:"unbreaking",lvl:20},{id:"fortune",lvl:10},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative] netherite_pickaxe{display:{Name:"{\"text\":\"The Netherite Pickaxe L2\"}",Lore:["{\"text\":\"Efficiency L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Sharpness XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Silk Touch\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"efficiency",lvl:50},{id:"sharpness",lvl:30},{id:"unbreaking",lvl:20},{id:"silktouch",lvl:1},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative] netherite_axe{display:{Name:"{\"text\":\"Netherite Axe A\"}"},Enchantments:[{id:"sharpness",lvl:5},{id:"efficiency",lvl:5},{id:"fortune",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_axe{display:{Name:"{\"text\":\"Netherite Axe B\"}"},Enchantments:[{id:"sharpness",lvl:5},{id:"efficiency",lvl:5},{id:"silk_touch",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_axe{display:{Name:"{\"text\":\"Netherite Axe C\"}"},Enchantments:[{id:"smite",lvl:5},{id:"efficiency",lvl:5},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_axe{display:{Name:"{\"text\":\"Netherite Axe D\"}"},Enchantments:[{id:"bane_of_arthropods",lvl:5},{id:"efficiency",lvl:5},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_axe{display:{Name:"{\"text\":\"Netherite Axe X\"}"},Enchantments:[{id:"sharpness",lvl:10},{id:"efficiency",lvl:10},{id:"fortune",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_axe{display:{Name:"{\"text\":\"Netherite Axe Y\"}"},Enchantments:[{id:"sharpness",lvl:10},{id:"efficiency",lvl:10},{id:"silk_touch",lvl:1},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_axe{display:{Name:"{\"text\":\"The Netherite Axe L1\"}",Lore:["{\"text\":\"Sharpness L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Efficiency L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fortune X\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"sharpness",lvl:50},{id:"efficiency",lvl:50},{id:"unbreaking",lvl:20},{id:"fortune",lvl:10},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative] netherite_axe{display:{Name:"{\"text\":\"The Netherite Axe L2\"}",Lore:["{\"text\":\"Sharpness L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Efficiency L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Silk Touch\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"sharpness",lvl:50},{id:"efficiency",lvl:50},{id:"unbreaking",lvl:20},{id:"silktouch",lvl:1},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative] netherite_shovel{display:{Name:"{\"text\":\"Netherite Shovel A\"}"},Enchantments:[{id:"efficiency",lvl:5},{id:"sharpness",lvl:5},{id:"fortune",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_shovel{display:{Name:"{\"text\":\"Netherite Shovel B\"}"},Enchantments:[{id:"efficiency",lvl:5},{id:"sharpness",lvl:5},{id:"silk_touch",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_shovel{display:{Name:"{\"text\":\"Netherite Shovel X\"}"},Enchantments:[{id:"efficiency",lvl:10},{id:"sharpness",lvl:10},{id:"fortune",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_shovel{display:{Name:"{\"text\":\"Netherite Shovel Y\"}"},Enchantments:[{id:"efficiency",lvl:10},{id:"sharpness",lvl:10},{id:"silk_touch",lvl:1},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_shovel{display:{Name:"{\"text\":\"The Netherite Shovel L1\"}",Lore:["{\"text\":\"Efficiency L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Sharpness XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fortune X\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"efficiency",lvl:50},{id:"sharpness",lvl:30},{id:"unbreaking",lvl:20},{id:"fortune",lvl:10},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative] netherite_shovel{display:{Name:"{\"text\":\"The Netherite Shovel L2\"}",Lore:["{\"text\":\"Efficiency L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Sharpness XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Silk Touch\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"efficiency",lvl:50},{id:"sharpness",lvl:30},{id:"unbreaking",lvl:20},{id:"silktouch",lvl:1},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative] netherite_hoe{display:{Name:"{\"text\":\"Netherite Hoe A\"}"},Enchantments:[{id:"efficiency",lvl:5},{id:"sharpness",lvl:5},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_hoe{display:{Name:"{\"text\":\"Netherite Hoe X\"}"},Enchantments:[{id:"efficiency",lvl:10},{id:"sharpness",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_hoe{display:{Name:"{\"text\":\"The Netherite Hoe L\"}",Lore:["{\"text\":\"Efficiency L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Sharpness XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"efficiency",lvl:50},{id:"sharpness",lvl:30},{id:"unbreaking",lvl:20},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative] netherite_sword{display:{Name:"{\"text\":\"Netherite Sword A\"}"},Enchantments:[{id:"sharpness",lvl:5},{id:"sweeping",lvl:3},{id:"fire_aspect",lvl:2},{id:"knockback",lvl:2},{id:"looting",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_sword{display:{Name:"{\"text\":\"Netherite Sword B\"}"},Enchantments:[{id:"smite",lvl:5},{id:"sweeping",lvl:3},{id:"fire_aspect",lvl:2},{id:"knockback",lvl:2},{id:"looting",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_sword{display:{Name:"{\"text\":\"Netherite Sword C\"}"},Enchantments:[{id:"bane_of_arthropods",lvl:5},{id:"sweeping",lvl:3},{id:"fire_aspect",lvl:2},{id:"knockback",lvl:2},{id:"looting",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_sword{display:{Name:"{\"text\":\"Netherite Sword X\"}"},Enchantments:[{id:"sharpness",lvl:10},{id:"sweeping",lvl:10},{id:"fire_aspect",lvl:10},{id:"knockback",lvl:10},{id:"looting",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}


give @p[gamemode=creative] netherite_sword{display:{Name:"{\"text\":\"The Netherite Sword L\"}",Lore:["{\"text\":\"Sharpness L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Smite XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Bane of Arthropods XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Sweeping Edge XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fire Aspect XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Looting X\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Knockback V\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"sharpness",lvl:50},{id:"smite",lvl:30},{id:"bane_of_arthropods",lvl:30},{id:"sweeping",lvl:30},{id:"fire_aspect",lvl:20},{id:"unbreaking",lvl:20},{id:"looting",lvl:10},{id:"knockback",lvl:5},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative] netherite_helmet{display:{Name:"{\"text\":\"Netherite Helmet A\"}"},Enchantments:[{id:"protection",lvl:4},{id:"thorns",lvl:3},{id:"respiration",lvl:3},{id:"aqua_affinity",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_helmet{display:{Name:"{\"text\":\"Netherite Helmet B\"}"},Enchantments:[{id:"projectile_protection",lvl:4},{id:"thorns",lvl:3},{id:"respiration",lvl:3},{id:"aqua_affinity",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_helmet{display:{Name:"{\"text\":\"Netherite Helmet C\"}"},Enchantments:[{id:"fire_protection",lvl:4},{id:"thorns",lvl:3},{id:"respiration",lvl:3},{id:"aqua_affinity",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_helmet{display:{Name:"{\"text\":\"Netherite Helmet D\"}"},Enchantments:[{id:"blast_protection",lvl:4},{id:"thorns",lvl:3},{id:"respiration",lvl:3},{id:"aqua_affinity",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_helmet{display:{Name:"{\"text\":\"Netherite Helmet X\"}"},Enchantments:[{id:"protection",lvl:10},{id:"thorns",lvl:10},{id:"respiration",lvl:10},{id:"aqua_affinity",lvl:1},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_helmet{display:{Name:"{\"text\":\"The Netherite Helmet L\"}",Lore:["{\"text\":\"Protection L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fire Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Blast Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Projectile Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Respiration XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Aqua Affinity\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"protection",lvl:50},{id:"fire_protection",lvl:30},{id:"blast_protection",lvl:30},{id:"projectile_protection",lvl:30},{id:"unbreaking",lvl:20},{id:"respiration",lvl:20},{id:"aqua_affinity",lvl:1},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative] netherite_chestplate{display:{Name:"{\"text\":\"Netherite Chestplate A\"}"},Enchantments:[{id:"protection",lvl:4},{id:"thorns",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_chestplate{display:{Name:"{\"text\":\"Netherite Chestplate B\"}"},Enchantments:[{id:"projectile_protection",lvl:4},{id:"thorns",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_chestplate{display:{Name:"{\"text\":\"Netherite Chestplate C\"}"},Enchantments:[{id:"fire_protection",lvl:4},{id:"thorns",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_chestplate{display:{Name:"{\"text\":\"Netherite Chestplate D\"}"},Enchantments:[{id:"blast_protection",lvl:4},{id:"thorns",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_chestplate{display:{Name:"{\"text\":\"Netherite Chestplate X\"}"},Enchantments:[{id:"protection",lvl:10},{id:"thorns",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_chestplate{display:{Name:"{\"text\":\"The Netherite Chestplate L\"}",Lore:["{\"text\":\"Protection L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fire Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Blast Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Projectile Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Thorns XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"protection",lvl:50},{id:"fire_protection",lvl:30},{id:"blast_protection",lvl:30},{id:"projectile_protection",lvl:30},{id:"unbreaking",lvl:20},{id:"thorns",lvl:20},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative] netherite_leggings{display:{Name:"{\"text\":\"Netherite Leggings A\"}"},Enchantments:[{id:"protection",lvl:4},{id:"thorns",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_leggings{display:{Name:"{\"text\":\"Netherite Leggings B\"}"},Enchantments:[{id:"projectile_protection",lvl:4},{id:"thorns",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_leggings{display:{Name:"{\"text\":\"Netherite Leggings C\"}"},Enchantments:[{id:"fire_protection",lvl:4},{id:"thorns",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_leggings{display:{Name:"{\"text\":\"Netherite Leggings D\"}"},Enchantments:[{id:"blast_protection",lvl:4},{id:"thorns",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_leggings{display:{Name:"{\"text\":\"Netherite Leggings X\"}"},Enchantments:[{id:"protection",lvl:10},{id:"thorns",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_leggings{display:{Name:"{\"text\":\"The Netherite Leggings L\"}",Lore:["{\"text\":\"Protection L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fire Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Blast Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Projectile Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Thorns XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"protection",lvl:50},{id:"fire_protection",lvl:30},{id:"blast_protection",lvl:30},{id:"projectile_protection",lvl:30},{id:"unbreaking",lvl:20},{id:"thorns",lvl:20},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative] netherite_boots{display:{Name:"{\"text\":\"Netherite Boots A\"}"},Enchantments:[{id:"protection",lvl:4},{id:"thorns",lvl:3},{id:"feather_falling",lvl:4},{id:"soul_speed",lvl:3},{id:"depth_strider",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_boots{display:{Name:"{\"text\":\"Netherite Boots B\"}"},Enchantments:[{id:"projectile_protection",lvl:4},{id:"thorns",lvl:3},{id:"feather_falling",lvl:4},{id:"soul_speed",lvl:3},{id:"depth_strider",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_boots{display:{Name:"{\"text\":\"Netherite Boots C\"}"},Enchantments:[{id:"fire_protection",lvl:4},{id:"thorns",lvl:3},{id:"feather_falling",lvl:4},{id:"soul_speed",lvl:3},{id:"depth_strider",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_boots{display:{Name:"{\"text\":\"Netherite Boots D\"}"},Enchantments:[{id:"blast_protection",lvl:4},{id:"thorns",lvl:3},{id:"feather_falling",lvl:4},{id:"soul_speed",lvl:3},{id:"depth_strider",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_boots{display:{Name:"{\"text\":\"Netherite Boots E\"}"},Enchantments:[{id:"protection",lvl:4},{id:"thorns",lvl:3},{id:"feather_falling",lvl:4},{id:"soul_speed",lvl:3},{id:"frost_walker",lvl:2},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_boots{display:{Name:"{\"text\":\"Netherite Boots X\"}"},Enchantments:[{id:"protection",lvl:10},{id:"thorns",lvl:10},{id:"feather_falling",lvl:10},{id:"soul_speed",lvl:3},{id:"depth_strider",lvl:3},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_boots{display:{Name:"{\"text\":\"Netherite Boots Y\"}"},Enchantments:[{id:"protection",lvl:10},{id:"thorns",lvl:10},{id:"feather_falling",lvl:10},{id:"soul_speed",lvl:3},{id:"frost_walker",lvl:2},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative] netherite_boots{display:{Name:"{\"text\":\"The Netherite Boots L\"}",Lore:["{\"text\":\"Protection L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fire Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Blast Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Projectile Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Soul Speed XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Depth Strider XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"protection",lvl:50},{id:"fire_protection",lvl:30},{id:"blast_protection",lvl:30},{id:"projectile_protection",lvl:30},{id:"unbreaking",lvl:20},{id:"soul_speed",lvl:20},{id:"depth_strider",lvl:20},{id:"mending",lvl:1}],HideFlags:1}
