
give @p[gamemode=creative,distance=..3] trident{display:{Name:"{\"text\":\"Trident\"}"}}
give @p[gamemode=creative,distance=..3] trident{display:{Name:"{\"text\":\"Trident A\"}"},Enchantments:[{id:"loyalty",lvl:3},{id:"channeling",lvl:1},{id:"impaling",lvl:5},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] trident{display:{Name:"{\"text\":\"Trident B\"}"},Enchantments:[{id:"riptide",lvl:3},{id:"impaling",lvl:5},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] trident{display:{Name:"{\"text\":\"Trident X1\"}"},Enchantments:[{id:"loyalty",lvl:10},{id:"channeling",lvl:1},{id:"impaling",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] trident{display:{Name:"{\"text\":\"Trident X2\"}"},Enchantments:[{id:"riptide",lvl:10},{id:"impaling",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] trident{display:{Name:"{\"text\":\"The Trident L1\"}",Lore:["{\"text\":\"Loyalty L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Impaling L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Channeling\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"loyalty",lvl:50},{id:"impaling",lvl:50},{id:"unbreaking",lvl:20},{id:"channeling",lvl:1},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative,distance=..3] trident{display:{Name:"{\"text\":\"The Trident L2\"}",Lore:["{\"text\":\"Riptide L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Impaling L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"riptide",lvl:50},{id:"impaling",lvl:50},{id:"unbreaking",lvl:20},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] bow{display:{Name:"{\"text\":\"Bow\"}"}}
give @p[gamemode=creative,distance=..3] bow{display:{Name:"{\"text\":\"Bow A\"}"},Enchantments:[{id:"power",lvl:5},{id:"punch",lvl:2},{id:"flame",lvl:1},{id:"infinity",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] bow{display:{Name:"{\"text\":\"Bow X\"}"},Enchantments:[{id:"power",lvl:10},{id:"punch",lvl:10},{id:"flame",lvl:1},{id:"infinity",lvl:1},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] bow{display:{Name:"{\"text\":\"The Bow L\"}",Lore:["{\"text\":\"Power L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Punch X\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Flame\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Infinity\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"power",lvl:50},{id:"unbreaking",lvl:20},{id:"punch",lvl:10},{id:"flame",lvl:1},{id:"infinity",lvl:1},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] crossbow{display:{Name:"{\"text\":\"Crossbow\"}"}}
give @p[gamemode=creative,distance=..3] crossbow{display:{Name:"{\"text\":\"Crossbow A\"}"},Enchantments:[{id:"piercing",lvl:4},{id:"quick_charge",lvl:3},{id:"multishot",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] crossbow{display:{Name:"{\"text\":\"Crossbow X\"}"},Enchantments:[{id:"piercing",lvl:10},{id:"quick_charge",lvl:5},{id:"multishot",lvl:1},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] crossbow{display:{Name:"{\"text\":\"The Crossbow L\"}",Lore:["{\"text\":\"Piercing L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Quick Charge V\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Multishot\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"piercing",lvl:50},{id:"unbreaking",lvl:20},{id:"quick_charge",lvl:5},{id:"multishot",lvl:1},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] shield{display:{Name:"{\"text\":\"Shield\"}"}}
give @p[gamemode=creative,distance=..3] shield{display:{Name:"{\"text\":\"Shield A\"}"},Enchantments:[{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] shield{display:{Name:"{\"text\":\"Shield X\"}"},Enchantments:[{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] shield{display:{Name:"{\"text\":\"The Shield L\"}",Lore:["{\"text\":\"Unbreaking L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"unbreaking",lvl:50},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] elytra{display:{Name:"{\"text\":\"Elytra\"}"}}
give @p[gamemode=creative,distance=..3] elytra{display:{Name:"{\"text\":\"Elytra A\"}"},Enchantments:[{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] elytra{display:{Name:"{\"text\":\"Elytra X\"}"},Enchantments:[{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] elytra{display:{Name:"{\"text\":\"The Elytra L\"}",Lore:["{\"text\":\"Unbreaking L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"unbreaking",lvl:50},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] turtle_helmet{display:{Name:"{\"text\":\"Turtle Helmet\"}"}}
give @p[gamemode=creative,distance=..3] turtle_helmet{display:{Name:"{\"text\":\"Turtle Helmet A\"}"},Enchantments:[{id:"protection",lvl:4},{id:"thorns",lvl:3},{id:"respiration",lvl:3},{id:"aqua_affinity",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] turtle_helmet{display:{Name:"{\"text\":\"Turtle Helmet X\"}"},Enchantments:[{id:"protection",lvl:10},{id:"thorns",lvl:10},{id:"respiration",lvl:10},{id:"aqua_affinity",lvl:1},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] turtle_helmet{display:{Name:"{\"text\":\"The Turtle Helmet L\"}",Lore:["{\"text\":\"Protection L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fire Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Blast Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Projectile Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Respiration XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Aqua Affinity\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"protection",lvl:50},{id:"fire_protection",lvl:30},{id:"blast_protection",lvl:30},{id:"projectile_protection",lvl:30},{id:"unbreaking",lvl:20},{id:"respiration",lvl:20},{id:"aqua_affinity",lvl:1},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] shears{display:{Name:"{\"text\":\"Shears\"}"}}
give @p[gamemode=creative,distance=..3] shears{display:{Name:"{\"text\":\"Shears A\"}"},Enchantments:[{id:"efficiency",lvl:5},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] shears{display:{Name:"{\"text\":\"Shears X\"}"},Enchantments:[{id:"efficiency",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] shears{display:{Name:"{\"text\":\"The Shears L\"}",Lore:["{\"text\":\"Efficiency L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"efficiency",lvl:50},{id:"unbreaking",lvl:20},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] flint_and_steel{display:{Name:"{\"text\":\"Flint and Steel\"}"}}
give @p[gamemode=creative,distance=..3] flint_and_steel{display:{Name:"{\"text\":\"Flint and Steel A\"}"},Enchantments:[{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] flint_and_steel{display:{Name:"{\"text\":\"Flint and Steel X\"}"},Enchantments:[{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] flint_and_steel{display:{Name:"{\"text\":\"The Flint and Steel L\"}",Lore:["{\"text\":\"Unbreaking L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"unbreaking",lvl:50},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] fishing_rod{display:{Name:"{\"text\":\"Fishing Rod\"}"}}
give @p[gamemode=creative,distance=..3] fishing_rod{display:{Name:"{\"text\":\"Fishing Rod A\"}"},Enchantments:[{id:"luck_of_the_sea",lvl:3},{id:"lure",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] fishing_rod{display:{Name:"{\"text\":\"Fishing Rod X\"}"},Enchantments:[{id:"luck_of_the_sea",lvl:10},{id:"lure",lvl:5},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] fishing_rod{display:{Name:"{\"text\":\"The Fishing Rod L\"}",Lore:["{\"text\":\"Luck of the Sea L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Lure V\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"luck_of_the_sea",lvl:50},{id:"unbreaking",lvl:20},{id:"lure",lvl:5},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] carrot_on_a_stick{display:{Name:"{\"text\":\"Carrot on a Stick\"}"}}
give @p[gamemode=creative,distance=..3] carrot_on_a_stick{display:{Name:"{\"text\":\"Carrot on a Stick A\"}"},Enchantments:[{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] carrot_on_a_stick{display:{Name:"{\"text\":\"Carrot on a Stick X\"}"},Enchantments:[{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] carrot_on_a_stick{display:{Name:"{\"text\":\"The Carrot on a Stick L\"}",Lore:["{\"text\":\"Unbreaking L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"unbreaking",lvl:50},{id:"mending",lvl:1}],HideFlags:1}

give @p[gamemode=creative,distance=..3] warped_fungus_on_a_stick{display:{Name:"{\"text\":\"Warped Fungus on a Stick\"}"}}
give @p[gamemode=creative,distance=..3] warped_fungus_on_a_stick{display:{Name:"{\"text\":\"Warped Fungus on a Stick A\"}"},Enchantments:[{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] warped_fungus_on_a_stick{display:{Name:"{\"text\":\"Warped Fungus on a Stick X\"}"},Enchantments:[{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] warped_fungus_on_a_stick{display:{Name:"{\"text\":\"The Warped Fungus on a Stick L\"}",Lore:["{\"text\":\"Unbreaking L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"unbreaking",lvl:50},{id:"mending",lvl:1}],HideFlags:1}


give @p[gamemode=creative,distance=..3] diamond_sword{display:{Name:"{\"text\":\"Diamond Sword\"}"}}
give @p[gamemode=creative,distance=..3] diamond_sword{display:{Name:"{\"text\":\"Diamond Sword A\"}"},Enchantments:[{id:"sharpness",lvl:5},{id:"sweeping",lvl:3},{id:"fire_aspect",lvl:2},{id:"knockback",lvl:2},{id:"looting",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_sword{display:{Name:"{\"text\":\"Diamond Sword B\"}"},Enchantments:[{id:"smite",lvl:5},{id:"sweeping",lvl:3},{id:"fire_aspect",lvl:2},{id:"knockback",lvl:2},{id:"looting",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_sword{display:{Name:"{\"text\":\"Diamond Sword C\"}"},Enchantments:[{id:"bane_of_arthropods",lvl:5},{id:"sweeping",lvl:3},{id:"fire_aspect",lvl:2},{id:"knockback",lvl:2},{id:"looting",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_sword{display:{Name:"{\"text\":\"Diamond Sword X\"}"},Enchantments:[{id:"sharpness",lvl:10},{id:"sweeping",lvl:10},{id:"fire_aspect",lvl:10},{id:"knockback",lvl:10},{id:"looting",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_sword{display:{Name:"{\"text\":\"Diamond Sword 9000\"}"},Enchantments:[{id:"sharpness",lvl:9000},{id:"sweeping",lvl:10},{id:"fire_aspect",lvl:10},{id:"knockback",lvl:10},{id:"looting",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}

give @p[gamemode=creative,distance=..3] diamond_pickaxe{display:{Name:"{\"text\":\"Diamond Pickaxe\"}"}}
give @p[gamemode=creative,distance=..3] diamond_pickaxe{display:{Name:"{\"text\":\"Diamond Pickaxe A\"}"},Enchantments:[{id:"efficiency",lvl:5},{id:"fortune",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_pickaxe{display:{Name:"{\"text\":\"Diamond Pickaxe B\"}"},Enchantments:[{id:"efficiency",lvl:5},{id:"silk_touch",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_pickaxe{display:{Name:"{\"text\":\"Diamond Pickaxe X\"}"},Enchantments:[{id:"efficiency",lvl:10},{id:"fortune",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_pickaxe{display:{Name:"{\"text\":\"Diamond Pickaxe 99\"}"},Enchantments:[{id:"efficiency",lvl:99},{id:"fortune",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}

give @p[gamemode=creative,distance=..3] diamond_axe{display:{Name:"{\"text\":\"Diamond Axe\"}"}}
give @p[gamemode=creative,distance=..3] diamond_axe{display:{Name:"{\"text\":\"Diamond Axe A\"}"},Enchantments:[{id:"sharpness",lvl:5},{id:"efficiency",lvl:5},{id:"fortune",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_axe{display:{Name:"{\"text\":\"Diamond Axe B\"}"},Enchantments:[{id:"sharpness",lvl:5},{id:"efficiency",lvl:5},{id:"silk_touch",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_axe{display:{Name:"{\"text\":\"Diamond Axe C\"}"},Enchantments:[{id:"smite",lvl:5},{id:"efficiency",lvl:5},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_axe{display:{Name:"{\"text\":\"Diamond Axe D\"}"},Enchantments:[{id:"bane_of_arthropods",lvl:5},{id:"efficiency",lvl:5},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_axe{display:{Name:"{\"text\":\"Diamond Axe X\"}"},Enchantments:[{id:"sharpness",lvl:10},{id:"efficiency",lvl:10},{id:"fortune",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}

give @p[gamemode=creative,distance=..3] diamond_shovel{display:{Name:"{\"text\":\"Diamond Shovel\"}"}}
give @p[gamemode=creative,distance=..3] diamond_shovel{display:{Name:"{\"text\":\"Diamond Shovel A\"}"},Enchantments:[{id:"efficiency",lvl:5},{id:"fortune",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_shovel{display:{Name:"{\"text\":\"Diamond Shovel B\"}"},Enchantments:[{id:"efficiency",lvl:5},{id:"silk_touch",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_shovel{display:{Name:"{\"text\":\"Diamond Shovel X\"}"},Enchantments:[{id:"efficiency",lvl:10},{id:"fortune",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}

give @p[gamemode=creative,distance=..3] diamond_hoe{display:{Name:"{\"text\":\"Diamond Hoe\"}"}}
give @p[gamemode=creative,distance=..3] diamond_hoe{display:{Name:"{\"text\":\"Diamond Hoe A\"}"},Enchantments:[{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_hoe{display:{Name:"{\"text\":\"Diamond Hoe X\"}"},Enchantments:[{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}


give @p[gamemode=creative,distance=..3] diamond_helmet{display:{Name:"{\"text\":\"Diamond Helmet\"}"}}
give @p[gamemode=creative,distance=..3] diamond_helmet{display:{Name:"{\"text\":\"Diamond Helmet A\"}"},Enchantments:[{id:"protection",lvl:4},{id:"thorns",lvl:3},{id:"respiration",lvl:3},{id:"aqua_affinity",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_helmet{display:{Name:"{\"text\":\"Diamond Helmet B\"}"},Enchantments:[{id:"projectile_protection",lvl:4},{id:"thorns",lvl:3},{id:"respiration",lvl:3},{id:"aqua_affinity",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_helmet{display:{Name:"{\"text\":\"Diamond Helmet C\"}"},Enchantments:[{id:"fire_protection",lvl:4},{id:"thorns",lvl:3},{id:"respiration",lvl:3},{id:"aqua_affinity",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_helmet{display:{Name:"{\"text\":\"Diamond Helmet D\"}"},Enchantments:[{id:"blast_protection",lvl:4},{id:"thorns",lvl:3},{id:"respiration",lvl:3},{id:"aqua_affinity",lvl:1},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_helmet{display:{Name:"{\"text\":\"Diamond Helmet X\"}"},Enchantments:[{id:"protection",lvl:10},{id:"thorns",lvl:10},{id:"respiration",lvl:10},{id:"aqua_affinity",lvl:1},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}

give @p[gamemode=creative,distance=..3] diamond_chestplate{display:{Name:"{\"text\":\"Diamond Chestplate\"}"}}
give @p[gamemode=creative,distance=..3] diamond_chestplate{display:{Name:"{\"text\":\"Diamond Chestplate A\"}"},Enchantments:[{id:"protection",lvl:4},{id:"thorns",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_chestplate{display:{Name:"{\"text\":\"Diamond Chestplate B\"}"},Enchantments:[{id:"projectile_protection",lvl:4},{id:"thorns",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_chestplate{display:{Name:"{\"text\":\"Diamond Chestplate C\"}"},Enchantments:[{id:"fire_protection",lvl:4},{id:"thorns",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_chestplate{display:{Name:"{\"text\":\"Diamond Chestplate D\"}"},Enchantments:[{id:"blast_protection",lvl:4},{id:"thorns",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_chestplate{display:{Name:"{\"text\":\"Diamond Chestplate X\"}"},Enchantments:[{id:"protection",lvl:10},{id:"thorns",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}

give @p[gamemode=creative,distance=..3] diamond_leggings{display:{Name:"{\"text\":\"Diamond Leggings\"}"}}
give @p[gamemode=creative,distance=..3] diamond_leggings{display:{Name:"{\"text\":\"Diamond Leggings A\"}"},Enchantments:[{id:"protection",lvl:4},{id:"thorns",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_leggings{display:{Name:"{\"text\":\"Diamond Leggings B\"}"},Enchantments:[{id:"projectile_protection",lvl:4},{id:"thorns",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_leggings{display:{Name:"{\"text\":\"Diamond Leggings C\"}"},Enchantments:[{id:"fire_protection",lvl:4},{id:"thorns",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_leggings{display:{Name:"{\"text\":\"Diamond Leggings D\"}"},Enchantments:[{id:"blast_protection",lvl:4},{id:"thorns",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_leggings{display:{Name:"{\"text\":\"Diamond Leggings X\"}"},Enchantments:[{id:"protection",lvl:10},{id:"thorns",lvl:10},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}

give @p[gamemode=creative,distance=..3] diamond_boots{display:{Name:"{\"text\":\"Diamond Boots\"}"}}
give @p[gamemode=creative,distance=..3] diamond_boots{display:{Name:"{\"text\":\"Diamond Boots A\"}"},Enchantments:[{id:"protection",lvl:4},{id:"thorns",lvl:3},{id:"feather_falling",lvl:4},{id:"depth_strider",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_boots{display:{Name:"{\"text\":\"Diamond Boots B\"}"},Enchantments:[{id:"protection",lvl:4},{id:"thorns",lvl:3},{id:"feather_falling",lvl:4},{id:"frost_walker",lvl:2},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_boots{display:{Name:"{\"text\":\"Diamond Boots C\"}"},Enchantments:[{id:"projectile_protection",lvl:4},{id:"thorns",lvl:3},{id:"feather_falling",lvl:4},{id:"depth_strider",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_boots{display:{Name:"{\"text\":\"Diamond Boots D\"}"},Enchantments:[{id:"fire_protection",lvl:4},{id:"thorns",lvl:3},{id:"feather_falling",lvl:4},{id:"depth_strider",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_boots{display:{Name:"{\"text\":\"Diamond Boots E\"}"},Enchantments:[{id:"blast_protection",lvl:4},{id:"thorns",lvl:3},{id:"feather_falling",lvl:4},{id:"depth_strider",lvl:3},{id:"unbreaking",lvl:3},{id:"mending",lvl:1}]}
give @p[gamemode=creative,distance=..3] diamond_boots{display:{Name:"{\"text\":\"Diamond Boots X\"}"},Enchantments:[{id:"protection",lvl:10},{id:"thorns",lvl:10},{id:"feather_falling",lvl:10},{id:"depth_strider",lvl:3},{id:"unbreaking",lvl:10},{id:"mending",lvl:1}]}

give @p[gamemode=creative,distance=..3] netherite_axe{display:{Name:"{\"text\":\"The Netherite Axe L1\"}",Lore:["{\"text\":\"Sharpness L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Efficiency L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fortune X\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"sharpness",lvl:50},{id:"efficiency",lvl:50},{id:"unbreaking",lvl:20},{id:"fortune",lvl:10},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative,distance=..3] netherite_axe{display:{Name:"{\"text\":\"The Netherite Axe L2\"}",Lore:["{\"text\":\"Sharpness L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Efficiency L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Silk Touch\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"sharpness",lvl:50},{id:"efficiency",lvl:50},{id:"unbreaking",lvl:20},{id:"silktouch",lvl:1},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative,distance=..3] netherite_pickaxe{display:{Name:"{\"text\":\"The Netherite Pickaxe L1\"}",Lore:["{\"text\":\"Efficiency L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fortune X\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"efficiency",lvl:50},{id:"unbreaking",lvl:20},{id:"fortune",lvl:10},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative,distance=..3] netherite_pickaxe{display:{Name:"{\"text\":\"The Netherite Pickaxe L2\"}",Lore:["{\"text\":\"Efficiency L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Silk Touch\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"efficiency",lvl:50},{id:"unbreaking",lvl:20},{id:"silktouch",lvl:1},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative,distance=..3] netherite_shovel{display:{Name:"{\"text\":\"The Netherite Shovel L1\"}",Lore:["{\"text\":\"Efficiency L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fortune X\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"efficiency",lvl:50},{id:"unbreaking",lvl:20},{id:"fortune",lvl:10},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative,distance=..3] netherite_shovel{display:{Name:"{\"text\":\"The Netherite Shovel L2\"}",Lore:["{\"text\":\"Efficiency L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Silk Touch\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"efficiency",lvl:50},{id:"unbreaking",lvl:20},{id:"silktouch",lvl:1},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative,distance=..3] netherite_hoe{display:{Name:"{\"text\":\"The Netherite Hoe L\"}",Lore:["{\"text\":\"Efficiency L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"efficiency",lvl:50},{id:"unbreaking",lvl:20},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative,distance=..3] netherite_sword{display:{Name:"{\"text\":\"The Netherite Sword L\"}",Lore:["{\"text\":\"Sharpness L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Sweeping Edge XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fire Aspect XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Looting X\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Knockback V\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"sharpness",lvl:50},{id:"sweeping",lvl:30},{id:"fire_aspect",lvl:20},{id:"unbreaking",lvl:20},{id:"looting",lvl:10},{id:"knockback",lvl:5},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative,distance=..3] netherite_helmet{display:{Name:"{\"text\":\"The Netherite Helmet L\"}",Lore:["{\"text\":\"Protection L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fire Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Blast Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Projectile Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Respiration XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Aqua Affinity\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"protection",lvl:50},{id:"fire_protection",lvl:30},{id:"blast_protection",lvl:30},{id:"projectile_protection",lvl:30},{id:"unbreaking",lvl:20},{id:"respiration",lvl:20},{id:"aqua_affinity",lvl:1},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative,distance=..3] netherite_chestplate{display:{Name:"{\"text\":\"The Netherite Chestplate L\"}",Lore:["{\"text\":\"Protection L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fire Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Blast Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Projectile Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Thorns XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"protection",lvl:50},{id:"fire_protection",lvl:30},{id:"blast_protection",lvl:30},{id:"projectile_protection",lvl:30},{id:"unbreaking",lvl:20},{id:"thorns",lvl:20},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative,distance=..3] netherite_leggings{display:{Name:"{\"text\":\"The Netherite Leggings L\"}",Lore:["{\"text\":\"Protection L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fire Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Blast Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Projectile Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Thorns XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"protection",lvl:50},{id:"fire_protection",lvl:30},{id:"blast_protection",lvl:30},{id:"projectile_protection",lvl:30},{id:"unbreaking",lvl:20},{id:"thorns",lvl:20},{id:"mending",lvl:1}],HideFlags:1}
give @p[gamemode=creative,distance=..3] netherite_boots{display:{Name:"{\"text\":\"The Netherite Boots L\"}",Lore:["{\"text\":\"Protection L\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Fire Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Blast Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Projectile Protection XXX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Unbreaking XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Soul Speed XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Depth Strider XX\",\"color\":\"gray\",\"italic\":false}","{\"text\":\"Mending\",\"color\":\"gray\",\"italic\":false}"]},Enchantments:[{id:"protection",lvl:50},{id:"fire_protection",lvl:30},{id:"blast_protection",lvl:30},{id:"projectile_protection",lvl:30},{id:"unbreaking",lvl:20},{id:"soul_speed",lvl:20},{id:"depth_strider",lvl:20},{id:"mending",lvl:1}],HideFlags:1}
