scoreboard objectives remove Price
scoreboard objectives add Price dummy
scoreboard players set cobbled_deepslate_buy Price 75
scoreboard players set cobbled_deepslate_buy_16 Price 1200
scoreboard players set cobbled_deepslate_sell Price 15
scoreboard players set cobbled_deepslate_sell_64 Price 960
scoreboard players set cobblestone_buy Price 110
scoreboard players set cobblestone_buy_16 Price 1760
scoreboard players set cobblestone_sell Price 11
scoreboard players set cobblestone_sell_64 Price 704
scoreboard players set dripstone_block_sell Price 22
scoreboard players set dripstone_block_sell_64 Price 1408
scoreboard players set blackstone_buy Price 360
scoreboard players set blackstone_buy_16 Price 5760
scoreboard players set blackstone_sell Price 72
scoreboard players set blackstone_sell_64 Price 4608
scoreboard players set andesite_sell Price 82
scoreboard players set andesite_sell_64 Price 5248
scoreboard players set basalt_sell Price 72
scoreboard players set basalt_sell_64 Price 4608
scoreboard players set crying_obsidian_sell Price 1500
scoreboard players set crying_obsidian_sell_64 Price 96000
scoreboard players set deepslate_sell Price 29
scoreboard players set deepslate_sell_64 Price 1856
scoreboard players set diorite_buy Price 435
scoreboard players set diorite_buy_16 Price 6960
scoreboard players set diorite_sell Price 87
scoreboard players set diorite_sell_64 Price 5568
scoreboard players set dirt_buy Price 50
scoreboard players set dirt_buy_16 Price 800
scoreboard players set dirt_sell Price 10
scoreboard players set dirt_sell_64 Price 640
scoreboard players set end_stone_buy Price 600
scoreboard players set end_stone_buy_16 Price 9600
scoreboard players set end_stone_sell Price 120
scoreboard players set end_stone_sell_64 Price 7680
scoreboard players set glowstone_dust_buy Price 525
scoreboard players set glowstone_dust_buy_16 Price 8400
scoreboard players set glowstone_dust_sell Price 105
scoreboard players set glowstone_dust_sell_64 Price 6720
scoreboard players set grass_block_sell Price 50
scoreboard players set grass_block_sell_64 Price 3200
scoreboard players set gravel_sell Price 12
scoreboard players set gravel_sell_64 Price 768
scoreboard players set ice_sell Price 15
scoreboard players set ice_sell_64 Price 960
scoreboard players set netherrack_buy Price 150
scoreboard players set netherrack_buy_16 Price 2400
scoreboard players set netherrack_sell Price 15
scoreboard players set netherrack_sell_64 Price 960
scoreboard players set obsidian_buy Price 10000
scoreboard players set obsidian_buy_16 Price 160000
scoreboard players set obsidian_sell Price 500
scoreboard players set obsidian_sell_64 Price 32000
scoreboard players set quartz_buy Price 750
scoreboard players set quartz_buy_16 Price 12000
scoreboard players set quartz_sell Price 150
scoreboard players set quartz_sell_64 Price 9600
scoreboard players set red_sand_sell Price 25
scoreboard players set red_sand_sell_64 Price 1600
scoreboard players set sand_buy Price 120
scoreboard players set sand_buy_16 Price 1920
scoreboard players set sand_sell Price 12
scoreboard players set sand_sell_64 Price 768
scoreboard players set shroomlight_buy Price 2500
scoreboard players set shroomlight_buy_16 Price 40000
scoreboard players set shroomlight_sell Price 250
scoreboard players set shroomlight_sell_64 Price 16000
scoreboard players set smooth_stone_sell Price 29
scoreboard players set smooth_stone_sell_64 Price 1856
scoreboard players set soul_sand_buy Price 50
scoreboard players set soul_sand_buy_16 Price 800
scoreboard players set soul_sand_sell Price 25
scoreboard players set soul_sand_sell_64 Price 1600
scoreboard players set sponge_buy Price 50000
scoreboard players set sponge_buy_16 Price 800000
scoreboard players set sponge_sell Price 2500
scoreboard players set sponge_sell_64 Price 160000
scoreboard players set stone_buy Price 40
scoreboard players set stone_buy_16 Price 640
scoreboard players set stone_sell Price 20
scoreboard players set stone_sell_64 Price 1280
scoreboard players set white_wool_buy Price 51
scoreboard players set white_wool_buy_16 Price 816
scoreboard players set white_wool_sell Price 17
scoreboard players set white_wool_sell_64 Price 1088
scoreboard players set apple_buy Price 50
scoreboard players set apple_buy_16 Price 800
scoreboard players set apple_sell Price 25
scoreboard players set apple_sell_64 Price 1600
scoreboard players set bamboo_buy Price 28
scoreboard players set bamboo_buy_16 Price 448
scoreboard players set bamboo_sell Price 14
scoreboard players set bamboo_sell_64 Price 896
scoreboard players set beetroot_buy Price 54
scoreboard players set beetroot_buy_16 Price 864
scoreboard players set beetroot_sell Price 18
scoreboard players set beetroot_sell_64 Price 1152


scoreboard players set beetroot_seeds_sell Price 9
scoreboard players set beetroot_seeds_sell_64 Price 576
scoreboard players set brown_mushroom_buy Price 40
scoreboard players set brown_mushroom_buy_16 Price 640
scoreboard players set brown_mushroom_sell Price 20
scoreboard players set brown_mushroom_sell_64 Price 1280
scoreboard players set cactus_buy Price 34
scoreboard players set cactus_buy_16 Price 544
scoreboard players set cactus_sell Price 17
scoreboard players set cactus_sell_64 Price 1088
scoreboard players set carrot_buy Price 30
scoreboard players set carrot_buy_16 Price 480
scoreboard players set carrot_sell Price 15
scoreboard players set carrot_sell_64 Price 960
scoreboard players set chicken_sell Price 13
scoreboard players set chicken_sell_64 Price 832
scoreboard players set chorus_fruit_buy Price 2640
scoreboard players set chorus_fruit_buy_16 Price 42240
scoreboard players set chorus_fruit_sell Price 66
scoreboard players set chorus_fruit_sell_64 Price 4224
scoreboard players set cocoa_beans_buy Price 28
scoreboard players set cocoa_beans_buy_16 Price 448
scoreboard players set cocoa_beans_sell Price 14
scoreboard players set cocoa_beans_sell_64 Price 896
scoreboard players set cod_sell Price 15
scoreboard players set cod_sell_64 Price 960
scoreboard players set cooked_beef_buy Price 44
scoreboard players set cooked_beef_buy_16 Price 704
scoreboard players set cooked_beef_sell Price 22
scoreboard players set cooked_beef_sell_64 Price 1408
scoreboard players set cooked_chicken_buy Price 44
scoreboard players set cooked_chicken_buy_16 Price 704
scoreboard players set cooked_chicken_sell Price 22
scoreboard players set cooked_chicken_sell_64 Price 1408
scoreboard players set cooked_cod_buy Price 48
scoreboard players set cooked_cod_buy_16 Price 768
scoreboard players set cooked_cod_sell Price 24
scoreboard players set cooked_cod_sell_64 Price 1536
scoreboard players set cooked_mutton_buy Price 44
scoreboard players set cooked_mutton_buy_16 Price 704
scoreboard players set cooked_mutton_sell Price 22
scoreboard players set cooked_mutton_sell_64 Price 1408
scoreboard players set cooked_porkchop_buy Price 44
scoreboard players set cooked_porkchop_buy_16 Price 704
scoreboard players set cooked_porkchop_sell Price 22
scoreboard players set cooked_porkchop_sell_64 Price 1408
scoreboard players set cooked_rabbit_buy Price 44
scoreboard players set cooked_rabbit_buy_16 Price 704
scoreboard players set cooked_rabbit_sell Price 22
scoreboard players set cooked_rabbit_sell_64 Price 1408
scoreboard players set cooked_salmon_buy Price 54
scoreboard players set cooked_salmon_buy_16 Price 864
scoreboard players set cooked_salmon_sell Price 27
scoreboard players set cooked_salmon_sell_64 Price 1728
scoreboard players set crimson_fungus_buy Price 1800
scoreboard players set crimson_fungus_buy_16 Price 28800
scoreboard players set crimson_fungus_sell Price 90
scoreboard players set crimson_fungus_sell_64 Price 5760
scoreboard players set egg_buy Price 50
scoreboard players set egg_buy_16 Price 800
scoreboard players set egg_sell Price 25
scoreboard players set egg_sell_16 Price 400
scoreboard players set honey_bottle_buy Price 110
scoreboard players set honey_bottle_buy_16 Price 1760
scoreboard players set honey_bottle_sell Price 55
scoreboard players set honey_bottle_sell_16 Price 880
scoreboard players set honeycomb_buy Price 60
scoreboard players set honeycomb_buy_16 Price 960
scoreboard players set honeycomb_sell Price 30
scoreboard players set honeycomb_sell_64 Price 1920
scoreboard players set melon_slice_buy Price 18
scoreboard players set melon_slice_buy_16 Price 288
scoreboard players set melon_slice_sell Price 9
scoreboard players set melon_slice_sell_64 Price 576
scoreboard players set mutton_sell Price 12
scoreboard players set mutton_sell_64 Price 768
scoreboard players set nether_wart_buy Price 1250
scoreboard players set nether_wart_buy_16 Price 20000
scoreboard players set nether_wart_sell Price 50
scoreboard players set nether_wart_sell_64 Price 3200
scoreboard players set porkchop_sell Price 12
scoreboard players set porkchop_sell_64 Price 768
scoreboard players set potato_buy Price 30
scoreboard players set potato_buy_16 Price 480
scoreboard players set potato_sell Price 15
scoreboard players set potato_sell_64 Price 960
scoreboard players set pufferfish_buy Price 60
scoreboard players set pufferfish_buy_16 Price 960
scoreboard players set pufferfish_sell Price 30
scoreboard players set pufferfish_sell_64 Price 1920
scoreboard players set pumpkin_buy Price 110
scoreboard players set pumpkin_buy_16 Price 1760
scoreboard players set pumpkin_sell Price 55
scoreboard players set pumpkin_sell_64 Price 3520
scoreboard players set rabbit_sell Price 12
scoreboard players set rabbit_sell_64 Price 768
scoreboard players set red_mushroom_buy Price 40
scoreboard players set red_mushroom_buy_16 Price 640


scoreboard players set red_mushroom_sell Price 20
scoreboard players set red_mushroom_sell_64 Price 1280
scoreboard players set salmon_sell Price 17
scoreboard players set salmon_sell_64 Price 1088
scoreboard players set sugar_cane_buy Price 45
scoreboard players set sugar_cane_buy_16 Price 720
scoreboard players set sugar_cane_sell Price 15
scoreboard players set sugar_cane_sell_64 Price 960
scoreboard players set sweet_berries_buy Price 30
scoreboard players set sweet_berries_buy_16 Price 480
scoreboard players set sweet_berries_sell Price 15
scoreboard players set sweet_berries_sell_64 Price 960
scoreboard players set tropical_fish_sell Price 22
scoreboard players set tropical_fish_sell_64 Price 1408
scoreboard players set warped_fungus_buy Price 360
scoreboard players set warped_fungus_buy_16 Price 5760
scoreboard players set warped_fungus_sell Price 90
scoreboard players set warped_fungus_sell_64 Price 5760
scoreboard players set wheat_buy Price 45
scoreboard players set wheat_buy_16 Price 720
scoreboard players set wheat_sell Price 15
scoreboard players set wheat_sell_64 Price 960
scoreboard players set wheat_seeds_sell Price 5
scoreboard players set wheat_seeds_sell_64 Price 320
scoreboard players set arrow_buy Price 140
scoreboard players set arrow_buy_16 Price 2240
scoreboard players set arrow_sell Price 14
scoreboard players set arrow_sell_64 Price 896
scoreboard players set blaze_rod_buy Price 7500
scoreboard players set blaze_rod_buy_16 Price 120000
scoreboard players set blaze_rod_sell Price 750
scoreboard players set blaze_rod_sell_64 Price 48000
scoreboard players set bone_buy Price 44
scoreboard players set bone_buy_16 Price 704
scoreboard players set bone_sell Price 22
scoreboard players set bone_sell_64 Price 1408
scoreboard players set clay_ball_buy Price 50
scoreboard players set clay_ball_buy_16 Price 800
scoreboard players set clay_ball_sell Price 25
scoreboard players set clay_ball_sell_64 Price 1600
scoreboard players set diamond_horse_armor_buy Price 50000
scoreboard players set diamond_horse_armor_buy_16 Price 800000
scoreboard players set diamond_horse_armor_sell Price 25000
scoreboard players set diamond_horse_armor_sell_64 Price 1600000
scoreboard players set ender_pearl_buy Price 64
scoreboard players set ender_pearl_buy_16 Price 1024
scoreboard players set ender_pearl_sell Price 32
scoreboard players set ender_pearl_sell_16 Price 512
scoreboard players set feather_buy Price 45
scoreboard players set feather_buy_16 Price 720
scoreboard players set feather_sell Price 15
scoreboard players set feather_sell_64 Price 960
scoreboard players set flint_buy Price 30
scoreboard players set flint_buy_16 Price 480
scoreboard players set flint_sell Price 15
scoreboard players set flint_sell_64 Price 960
scoreboard players set ghast_tear_buy Price 5000
scoreboard players set ghast_tear_buy_16 Price 80000
scoreboard players set ghast_tear_sell Price 2500
scoreboard players set ghast_tear_sell_64 Price 160000
scoreboard players set golden_horse_armor_buy Price 36000
scoreboard players set golden_horse_armor_buy_16 Price 576000
scoreboard players set golden_horse_armor_sell Price 18000
scoreboard players set golden_horse_armor_sell_64 Price 1152000
scoreboard players set gunpowder_buy Price 56
scoreboard players set gunpowder_buy_16 Price 896
scoreboard players set gunpowder_sell Price 28
scoreboard players set gunpowder_sell_64 Price 1792
scoreboard players set ink_sac_buy Price 30
scoreboard players set ink_sac_buy_16 Price 480
scoreboard players set ink_sac_sell Price 15
scoreboard players set ink_sac_sell_64 Price 960
scoreboard players set iron_horse_armor_buy Price 30000
scoreboard players set iron_horse_armor_buy_16 Price 480000
scoreboard players set iron_horse_armor_sell Price 15000
scoreboard players set iron_horse_armor_sell_64 Price 960000
scoreboard players set lead_buy Price 128
scoreboard players set lead_buy_16 Price 2048
scoreboard players set lead_sell Price 64
scoreboard players set lead_sell_64 Price 4096
scoreboard players set leather_buy Price 60
scoreboard players set leather_buy_16 Price 960
scoreboard players set leather_sell Price 20
scoreboard players set leather_sell_64 Price 1280
scoreboard players set name_tag_buy Price 2000
scoreboard players set name_tag_buy_16 Price 32000
scoreboard players set name_tag_sell Price 1000
scoreboard players set name_tag_sell_64 Price 64000
scoreboard players set nether_star_buy Price 200000
scoreboard players set nether_star_buy_16 Price 3200000
scoreboard players set nether_star_sell Price 100000
scoreboard players set nether_star_sell_64 Price 6400000
scoreboard players set phantom_membrane_buy Price 60
scoreboard players set phantom_membrane_buy_16 Price 960
scoreboard players set phantom_membrane_sell Price 30
scoreboard players set phantom_membrane_sell_64 Price 1920
scoreboard players set prismarine_crystals_buy Price 10000
scoreboard players set prismarine_crystals_buy_16 Price 160000


scoreboard players set prismarine_crystals_sell Price 5000
scoreboard players set prismarine_crystals_sell_64 Price 320000
scoreboard players set prismarine_shard_buy Price 1400
scoreboard players set prismarine_shard_buy_16 Price 22400
scoreboard players set prismarine_shard_sell Price 700
scoreboard players set prismarine_shard_sell_64 Price 44800
scoreboard players set rabbit_foot_buy Price 30
scoreboard players set rabbit_foot_buy_16 Price 480
scoreboard players set rabbit_foot_sell Price 15
scoreboard players set rabbit_foot_sell_64 Price 960
scoreboard players set rotten_flesh_buy Price 44
scoreboard players set rotten_flesh_buy_16 Price 704
scoreboard players set rotten_flesh_sell Price 22
scoreboard players set rotten_flesh_sell_64 Price 1408
scoreboard players set saddle_buy Price 15000
scoreboard players set saddle_buy_16 Price 240000
scoreboard players set saddle_sell Price 7500
scoreboard players set saddle_sell_64 Price 480000
scoreboard players set scute_buy Price 100
scoreboard players set scute_buy_16 Price 1600
scoreboard players set scute_sell Price 50
scoreboard players set scute_sell_64 Price 3200
scoreboard players set slime_ball_buy Price 56
scoreboard players set slime_ball_buy_16 Price 896
scoreboard players set slime_ball_sell Price 28
scoreboard players set slime_ball_sell_64 Price 1792
scoreboard players set snowball_buy Price 44
scoreboard players set snowball_buy_16 Price 704
scoreboard players set snowball_sell Price 22
scoreboard players set snowball_sell_16 Price 352
scoreboard players set spider_eye_buy Price 50
scoreboard players set spider_eye_buy_16 Price 800
scoreboard players set spider_eye_sell Price 25
scoreboard players set spider_eye_sell_64 Price 1600
scoreboard players set string_buy Price 44
scoreboard players set string_buy_16 Price 704
scoreboard players set string_sell Price 22
scoreboard players set string_sell_64 Price 1408
scoreboard players set turtle_egg_buy Price 120
scoreboard players set turtle_egg_buy_16 Price 1920
scoreboard players set turtle_egg_sell Price 60
scoreboard players set turtle_egg_sell_64 Price 3840
scoreboard players set acacia_log_buy Price 300
scoreboard players set acacia_log_buy_16 Price 4800
scoreboard players set acacia_log_sell Price 30
scoreboard players set acacia_log_sell_64 Price 1920
scoreboard players set birch_log_buy Price 300
scoreboard players set birch_log_buy_16 Price 4800
scoreboard players set birch_log_sell Price 30
scoreboard players set birch_log_sell_64 Price 1920
scoreboard players set dark_oak_log_buy Price 300
scoreboard players set dark_oak_log_buy_16 Price 4800
scoreboard players set dark_oak_log_sell Price 30
scoreboard players set dark_oak_log_sell_64 Price 1920
scoreboard players set jungle_log_buy Price 300
scoreboard players set jungle_log_buy_16 Price 4800
scoreboard players set jungle_log_sell Price 30
scoreboard players set jungle_log_sell_64 Price 1920
scoreboard players set oak_log_buy Price 300
scoreboard players set oak_log_buy_16 Price 4800
scoreboard players set oak_log_sell Price 30
scoreboard players set oak_log_sell_64 Price 1920
scoreboard players set spruce_log_buy Price 300
scoreboard players set spruce_log_buy_16 Price 4800
scoreboard players set spruce_log_sell Price 30
scoreboard players set spruce_log_sell_64 Price 1920
scoreboard players set crimson_stem_buy Price 900
scoreboard players set crimson_stem_buy_16 Price 14400
scoreboard players set crimson_stem_sell Price 90
scoreboard players set crimson_stem_sell_64 Price 5760
scoreboard players set warped_stem_buy Price 900
scoreboard players set warped_stem_buy_16 Price 14400
scoreboard players set warped_stem_sell Price 90
scoreboard players set warped_stem_sell_64 Price 5760
scoreboard players set coal_buy Price 350
scoreboard players set coal_buy_16 Price 5600
scoreboard players set coal_sell Price 35
scoreboard players set coal_sell_64 Price 2240
scoreboard players set redstone_buy Price 1050
scoreboard players set redstone_buy_16 Price 16800
scoreboard players set redstone_sell Price 105
scoreboard players set redstone_sell_64 Price 6720
scoreboard players set lapis_lazuli_buy Price 11250
scoreboard players set lapis_lazuli_buy_16 Price 180000
scoreboard players set lapis_lazuli_sell Price 225
scoreboard players set lapis_lazuli_sell_64 Price 14400
scoreboard players set amethyst_shard_buy Price 22500
scoreboard players set amethyst_shard_buy_16 Price 360000
scoreboard players set amethyst_shard_sell Price 450
scoreboard players set amethyst_shard_sell_64 Price 28800
scoreboard players set copper_ingot_buy Price 17500
scoreboard players set copper_ingot_buy_16 Price 280000
scoreboard players set copper_ingot_sell Price 350
scoreboard players set copper_ingot_sell_64 Price 22400
scoreboard players set iron_ingot_buy Price 22500
scoreboard players set iron_ingot_buy_16 Price 360000
scoreboard players set iron_ingot_sell Price 450
scoreboard players set iron_ingot_sell_64 Price 28800


scoreboard players set gold_ingot_buy Price 27500
scoreboard players set gold_ingot_buy_16 Price 440000
scoreboard players set gold_ingot_sell Price 550
scoreboard players set gold_ingot_sell_64 Price 35200
scoreboard players set emerald_buy Price 37500
scoreboard players set emerald_buy_16 Price 600000
scoreboard players set emerald_sell Price 750
scoreboard players set emerald_sell_64 Price 48000
scoreboard players set diamond_buy Price 125000
scoreboard players set diamond_buy_16 Price 2000000
scoreboard players set diamond_sell Price 2500
scoreboard players set diamond_sell_64 Price 160000
scoreboard players set netherite_ingot_buy Price 2500000
scoreboard players set netherite_ingot_buy_16 Price 40000000
scoreboard players set netherite_ingot_sell Price 50000
scoreboard players set netherite_ingot_sell_64 Price 3200000
scoreboard players set dragon_breath_buy Price 200000
scoreboard players set dragon_breath_buy_16 Price 3200000
scoreboard players set dragon_breath_sell Price 100000
scoreboard players set dragon_breath_sell_64 Price 6400000
scoreboard players set dragon_egg_sell Price 10000000
scoreboard players set dragon_egg_sell_64 Price 640000000
scoreboard players set elytra_sell Price 5000000
scoreboard players set elytra_sell_64 Price 320000000
scoreboard players set enchanted_golden_apple_buy Price 1000000
scoreboard players set enchanted_golden_apple_buy_16 Price 16000000
scoreboard players set enchanted_golden_apple_sell Price 500000
scoreboard players set enchanted_golden_apple_sell_64 Price 32000000
scoreboard players set experience_bottle_buy Price 20000
scoreboard players set experience_bottle_buy_16 Price 320000
scoreboard players set experience_bottle_sell Price 10000
scoreboard players set experience_bottle_sell_64 Price 640000
scoreboard players set heart_of_the_sea_buy Price 10000000
scoreboard players set heart_of_the_sea_buy_16 Price 160000000
scoreboard players set heart_of_the_sea_sell Price 5000000
scoreboard players set heart_of_the_sea_sell_64 Price 320000000
scoreboard players set nautilus_shell_buy Price 2000000
scoreboard players set nautilus_shell_buy_16 Price 32000000
scoreboard players set nautilus_shell_sell Price 1000000
scoreboard players set nautilus_shell_sell_64 Price 64000000
scoreboard players set shulker_shell_buy Price 100000000
scoreboard players set shulker_shell_buy_16 Price 1600000000
scoreboard players set shulker_shell_sell Price 500000
scoreboard players set shulker_shell_sell_64 Price 32000000
scoreboard players set totem_of_undying_buy Price 10000000
scoreboard players set totem_of_undying_sell Price 100000
scoreboard players set trident_buy Price 30000000
scoreboard players set trident_sell Price 300000
scoreboard players set wither_rose_buy Price 2000000
scoreboard players set wither_rose_buy_16 Price 32000000
scoreboard players set wither_rose_sell Price 1000000
scoreboard players set wither_rose_sell_64 Price 64000000
scoreboard players set wither_skeleton_skull_buy Price 6000000
scoreboard players set wither_skeleton_skull_buy_16 Price 96000000
scoreboard players set wither_skeleton_skull_sell Price 3000000
scoreboard players set wither_skeleton_skull_sell_64 Price 192000000
